Apa itu klasifikasi ? <br>
klasififikasi adalah proses untuk mengidentifikasi model untuk menghasilkan data dari proses training (Catatan : misalkan contoh ada data misalkan dalam bentuk gambar ada anjing ada kuncing nanti yang disebutkan adalah hewannya aja, seperti bunga jenisnya apa setosa verticolor virginica)

In [ ]:
from sklearn.datasets import load_iris
iris_datasets = load_iris()

In [ ]:
print(iris_datasets) ## menampilkan semua informasi yang ada pada datasets iris (seperti data, target, feature_names, target_names, DESCR, dan filename )
## [5.1, 3.5, 1.4, 0.2] [panjang sepal, lebar sepal, panjang petal, lebar petal]

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
print("Jenis Isian dari datasets iris = \n{}".format(iris_datasets.keys())) ## keys = seperti daftar isi dari iris_datasets

Jenis Isian dari datasets iris = 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print("Target name = \{}".format(iris_datasets['target_names']))

Target name = \['setosa' 'versicolor' 'virginica']


In [ ]:
print("feature names = \{}".format(iris_datasets['feature_names']))

feature names = \['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print("Data = \n{}".format(iris_datasets['data'][:5])) # menampilkan 5 baris pertama

Data = 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("Target = \n{}".format(iris_datasets['target']))##jenis bunga iris
## 0 = setosa, 1 = versicolor, 2 = virginica

Target = 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
#melihat tipe data # catatan mengubah string menjadi numerik
print("Type of data = {}".format(type(iris_datasets['data'])))
print("Target = {}".format(type(iris_datasets['target'])))

Type of data = <class 'numpy.ndarray'>
Target = <class 'numpy.ndarray'>


In [ ]:
print("ukuran data = {}".format(iris_datasets['data'].shape)) ## baris ada 150 dan 4 kolom
print("ukuran target = {}".format(iris_datasets['target'].shape)) ## 150 baris dan 1 kolom

ukuran data = (150, 4)
ukuran target = (150,)


#proses training dan testing

membagi data menjadi data untuk training dan data untuk testing
(untuk tes seberapa pintar ai, seperti kasi ai soal kita kasi jawaban, kaya mengklasifikasi bunga iris) kita akan menuliskan ukuran bunga nanti ai bakal coba jawab

dicoba membagi data training 75% dan data testing 25%

In [ ]:
from sklearn.model_selection import train_test_split
#x = data, y= target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets ['target'], test_size = 0.25 , random_state = 0)
#random_sate = 0  kalau di run ulang, isi data yang dibagi tetap sama

In [ ]:
#jumlah data training
print("x_train shape : {}".format(x_train.shape)) #Data = (sepal length, sepal widt, petal length)
print("y_train shape : {}".format(y_train.shape)) #Target = (setosa, versicolor, virginica)

x_train shape : (112, 4)
y_train shape : (112,)


In [ ]:
#jumlah data testing
print("x_test shape : {}".format(x_test.shape)) #Data = (sepal length, sepal widt, petal length)
print("y_test shape : {}".format(y_test.shape)) #Target = (setosa, versicolor, virginica)

x_test shape : (38, 4)
y_test shape : (38,)


#Proses training

In [ ]:
from sklearn.neighbors import KNeighborsClassifier #model untuk klasifikasi data seperti bunga
knn = KNeighborsClassifier(n_neighbors = 1)

In [ ]:
knn.fit(x_train,y_train) # proses training mengisi data

KNeighborsClassifier(n_neighbors=1)

melakukan prediksi

In [ ]:
import numpy as np
x_baru = np.array([[5, 2.1, 1, 0.2]])
prediksi = knn.predict(x_baru)
print("hasil prediksi knn = {}".format(prediksi))
print("hasil prediksi nama bunga = {}".format(iris_datasets['target_names'][prediksi]))

#evaluasi model

In [ ]:
y_pred = knn.predict(x_test) ##memprediksi tabel untuk data uji
print(y_pred)

In [ ]:
print("hasil akurasi model = {}".format(knn.score(x_test, y_test)))
#hasil akurasi 97%

hasil akurasi model = 0.9736842105263158


In [ ]:
from sklearn.model_selection import train_test_split
#x = data, y= target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets ['target'], test_size = 0.1 , random_state = 0)

In [ ]:
print("hasil akurasi model = {}".format(knn.score(x_test, y_test)))

hasil akurasi model = 1.0


#Tugas
Lakukan Klasifikasi menggunakan KNN pada dataset Breast Cancer dari Scikit Learn dengan pembagian data training 75% dan data testing 25%

In [2]:
from sklearn.datasets import load_breast_cancer
breast_cancer_datasets = load_breast_cancer()

In [3]:
print(breast_cancer_datasets)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
print("Jenis Isian dari datasets breast cancer = \n{}".format(breast_cancer_datasets.keys()))

Jenis Isian dari datasets breast cancer = 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print("Target name = \{}".format(breast_cancer_datasets['target_names']))

Target name = \['malignant' 'benign']


In [6]:
print("feature names = \{}".format(breast_cancer_datasets['feature_names']))

feature names = \['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [7]:
print("Data = \n{}".format(breast_cancer_datasets['data']))

Data = 
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
print("Target = \n{}".format(breast_cancer_datasets['target']))

Target = 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 

In [9]:
print("Type of data = {}".format(type(breast_cancer_datasets['data'])))
print("Target = {}".format(type(breast_cancer_datasets['target'])))

Type of data = <class 'numpy.ndarray'>
Target = <class 'numpy.ndarray'>


In [10]:
print("ukuran data = {}".format(breast_cancer_datasets['data'].shape)) ## baris ada 569 dan 30 kolom
print("ukuran target = {}".format(breast_cancer_datasets['target'].shape)) ## 569 baris dan 1 kolom

ukuran data = (569, 30)
ukuran target = (569,)


In [20]:
from sklearn.model_selection import train_test_split
#x = data, y= target
x_train, x_test, y_train, y_test = train_test_split(
    breast_cancer_datasets['data'],breast_cancer_datasets ['target'], test_size = 0.25 , random_state = 0)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [27]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [47]:
import numpy as np
x_baru = np.array([[17 , 22 , 23, 14, 15, 16, 17, 18, 19, 10, 11, 12 , 13, 14 , 15, 16, 17 ,18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])
prediksi = knn.predict(x_baru)
print("hasil prediksi knn = {}".format(prediksi))
print("hasil prediksi cancer = {}".format(breast_cancer_datasets['target_names'][prediksi]))

hasil prediksi knn = [1]
hasil prediksi cancer = ['benign']


#Evaluasi Model

In [48]:
y_pred = knn.predict(x_test)
print(y_pred)

[1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 1
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1
 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0]


In [49]:
print("hasil akurasi model = {}".format(knn.score(x_test, y_test)))
#hasil akurasi 91%

hasil akurasi model = 0.916083916083916
